In [2]:
import os 
import numpy as np
import earthpy as et

In [5]:
ls ~/earth-analytics/data/earthpy-downloads

avg-monthly-precip.txt  monthly-precip-2002-2013.csv  months.txt


In [6]:
os.chdir(os.path.join(et.io.HOME,"earth-analytics"))

In [8]:
fname = os.path.join("data","earthpy-downloads","avg-monthly-precip.txt")

avg_monthly_precip = np.loadtxt(fname)

print(avg_monthly_precip)

[0.7  0.75 1.85 2.93 3.05 2.02 1.93 1.62 1.84 1.31 1.39 0.84]


In [10]:
fname = os.path.join("data","earthpy-downloads","monthly-precip-2002-2013.csv")

precip_2002_2013 = np.loadtxt(fname,delimiter=",")

print(precip_2002_2013)

[[ 1.07  0.44  1.5   0.2   3.2   1.18  0.09  1.44  1.52  2.44  0.78  0.02]
 [ 0.27  1.13  1.72  4.14  2.66  0.61  1.03  1.4  18.16  2.24  0.29  0.5 ]]


In [12]:
avg_monthly_precip.shape

(12,)

In [13]:
avg_monthly_precip[11]

0.84

In [15]:
avg_monthly_precip[-1]

0.84

In [16]:
print(avg_monthly_precip[2:5])

[1.85 2.93 3.05]


In [17]:
precip_2002_2013.shape

(2, 12)

In [18]:
precip_2002_2013[1,2]

1.72

In [19]:
precip_2002_2013[1,11]

0.5

In [21]:
precip_2002_2013[-1,-1]

0.5

In [22]:
precip_2002_2013[0:1,0:2]

array([[1.07, 0.44]])

In [23]:
precip_2002_2013[0:2]

array([[ 1.07,  0.44,  1.5 ,  0.2 ,  3.2 ,  1.18,  0.09,  1.44,  1.52,
         2.44,  0.78,  0.02],
       [ 0.27,  1.13,  1.72,  4.14,  2.66,  0.61,  1.03,  1.4 , 18.16,
         2.24,  0.29,  0.5 ]])

In [24]:
precip_2002_2013[0:2, 0:1]

array([[1.07],
       [0.27]])

In [25]:
(precip_2002_2013[:2, :2])

array([[1.07, 0.44],
       [0.27, 1.13]])

In [27]:
(precip_2002_2013[0, :])

array([1.07, 0.44, 1.5 , 0.2 , 3.2 , 1.18, 0.09, 1.44, 1.52, 2.44, 0.78,
       0.02])

In [28]:
precip_2002 = precip_2002_2013[0, :]

print(precip_2002)

[1.07 0.44 1.5  0.2  3.2  1.18 0.09 1.44 1.52 2.44 0.78 0.02]


In [29]:
precip_2002_2013[1]

array([ 0.27,  1.13,  1.72,  4.14,  2.66,  0.61,  1.03,  1.4 , 18.16,
        2.24,  0.29,  0.5 ])